/**
 * Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface YtDownloadRequestDto { 
    url: string | null;
    title: string | null;
    album: string | null;
    artist: string | null;
    thumbnail: string | null;
    fileExtension: string | null;
}

